config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/home'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  resources :customers do
    resources :payments do
      post 'add_missing_payment', on: :collection
    end
  end
  root "pages#home"
  get "payments", to: "payments#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user
  has_many :payments, dependent: :destroy

  validates :subscription_fee, numericality: { greater_than: 0 }, presence: true
  validates_presence_of :subscription_fee, :start_date

  def up_to_date_with_payments?
    start_date = self.start_date
    end_date = Date.today
    required_payments = (end_date.year * 12 + end_date.month) - (start_date.year * 12 + start_date.month) + 1
    self.payments.where("payment_date >= ? AND payment_date <= ?", start_date, end_date).count >= required_payments
  end

  def missing_payments?
    missing_payments = []
    next_payment_date = self.start_date

    while next_payment_date <= Date.today
      # Verifica se existe um pagamento para o mês e ano de next_payment_date
      unless self.payments.where('extract(year from payment_date) = ? AND extract(month from payment_date) = ?', next_payment_date.year, next_payment_date.month).exists?
        missing_payments << next_payment_date
      end
      next_payment_date = next_payment_date.next_month.beginning_of_month
    end

    missing_payments
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :customer
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :customers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    payments_path
  end

  # Redireciona o usuário após cadastro
  def after_sign_up_path_for(resource)
    payments_path
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]

  # GET /customers or /customers.json
  def index
    @customers = current_user.customers.order(name: :asc)
  end

  # GET /customers/1 or /customers/1.json
  def show
    @payments = @customer.payments.order(payment_date: :desc)
  end

  # GET /customers/new
  def new
    @customer = current_user.customers.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = current_user.customers.build(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy!

    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:name, :phone, :subscription_fee, :start_date)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_customer, except: %i[index add_missing_payment]

  def index
    @customers_with_debts = current_user.customers.map do |customer|
      missing_payments = customer.missing_payments?.map do |date|
        { date: date, amount: customer.subscription_fee }
      end

      { customer: customer, missing_payments: missing_payments } unless missing_payments.empty?
    end.compact
  end

  def new
    @payment = @customer.payments.build
  end

  def create
    @payment = @customer.payments.build(payment_params)
    if @payment.save
      redirect_to @customer, notice: 'Payment was successfully created.'
    else
      render :new
    end
  end

  def add_missing_payment
    customer = Customer.find(params[:customer_id])
    @payment = customer.payments.build(payment_date: params[:payment_date], amount: params[:amount])
    if @payment.save
      redirect_back(fallback_location: customer_path(customer), notice: 'Payment was successfully added.')
    else
      redirect_back(fallback_location: customer_path(customer), alert: 'Failed to add payment.')
    end
  end

  private

    def set_customer
      @customer = current_user.customer.find(params[:customer_id])
    end

    def payment_params
      params.require(:payment).permit(:amount, :payment_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/customers/_customer.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Subscription Fee</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |customer| %>
      <tr id="<%= dom_id(customer) %>">
        <td>
          <%= link_to customer.name, customer_path(customer) %>
          <% unless customer.up_to_date_with_payments? %>
            <span class="ms-2 badge bg-danger">In Debt</span>
          <% end %>
        </td>
        <td><%= number_to_currency(customer.subscription_fee) %></td>
        <td>
          <%= link_to 'Edit', edit_customer_path(customer), class: "btn btn-primary btn-sm" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/customers/_customers_table.html.erb
<table class="table">
  <tbody>
    <% customers.each do |customer| %>
      <tr id="<%= dom_id(customer) %>">
        <td>
          <%= link_to customer.name, customer_path(customer) %>
          <% unless customer.up_to_date_with_payments? %>
            <span class="ms-2 badge bg-danger">In Debt</span>
          <% end %>
        </td>
        <td><%= number_to_currency(customer.subscription_fee) %></td>
        <td>
          <%= link_to 'Edit', edit_customer_path(customer), class: "btn btn-primary btn-sm" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/customers/_debt_status.html.erb
<% unless @customer.up_to_date_with_payments? %>
  <div class="mt-3 alert alert-danger" role="alert">
    Outstanding Debt
  </div>
<% end %>

app/views/customers/_form.html.erb
<%= form_with(model: customer, class: 'needs-validation', novalidate: true) do |form| %>
  <% if customer.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>
      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :phone, class: 'form-label' %>
    <%= form.text_field :phone, class: 'form-control' %>
  </div>

    <div class="mb-3">
      <%= form.label :subscription_fee, class: 'form-label' %>
      <%= form.text_field :subscription_fee, class: 'form-control' %>
    </div>

  <div class="mb-3">
    <%= form.label :start_date, class: 'form-label' %>
    <%= form.date_field :start_date, class: 'form-control', html5: true %>
  </div>

  <div class="d-flex justify-content-between">
    <%= link_to "Back", customers_path, class: "btn btn-secondary" %>
    <%= form.submit class: 'btn btn-success me-2' %>
  </div>

<% end %>

app/views/customers/_missing_payments.html.erb
<% if @customer.missing_payments?.any? %>
  <div class="alert alert-warning mt-4 mb-3" role="alert">
    <h4 class="alert-heading text-center">Customer's Outstanding Debts</h4>
  </div>
  <ul class="list-unstyled">
    <% @customer.missing_payments?.each do |date| %>
      <li class="d-flex justify-content-between py-2">
        <span class="flex-grow-1"><%= date.strftime("%B %Y") %></span>
        <%= form_with url: add_missing_payment_customer_payments_path(@customer), method: :post do |form| %>
          <%= form.hidden_field :payment_date, value: date %>
          <%= form.hidden_field :amount, value: @customer.subscription_fee %>
          <%= number_to_currency(@customer.subscription_fee) %><%= form.submit 'Paid', class: "btn btn-success btn-sm ms-2" %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/customers/_payments_table.html.erb
<% if @payments.exists? %>
  <table class="table">
    <thead>
      <tr>
        <th>Date</th>
        <th>Amount</th>
      </tr>
    </thead>
    <tbody>
      <% @payments.each do |payment| %>
        <tr>
          <td><%= payment.payment_date.strftime("%B %d, %Y") %></td>
          <td><%= number_to_currency(payment.amount) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No payments found.</p>
<% end %>

app/views/customers/edit.html.erb
<div class="container mt-4">
  <h1 class="mb-3">Editing Customer</h1>

  <%= render "form", customer: @customer %>

  <div class="mt-3">
    <%= button_to "Destroy this customer", @customer, method: :delete, form_class: "d-inline", class: "btn btn-danger", data: { confirm: "Are you sure?" } %>
  </div>
</div>

app/views/customers/index.html.erb
<% if current_user.customers.count.zero? %>

  <%= render "shared/welcome" %>

<% else %>

  <h2 class="pb-2 mb-0">Customers</h2>

  <%= render partial: "customers_table", locals: { customers: @customers } %>

  <div class="col-lg-6 col-xxl-4 my-5 mx-auto">
    <div class="d-grid gap-2">
      <%= link_to "New customer", new_customer_path, class: "btn btn-success" %>
    </div>
  </div>

<% end %>

app/views/customers/new.html.erb
<div class="container">
  <h1 class="mt-5">New Customer</h1>

  <%= render "form", customer: @customer %>

  <div class="mt-3">
    <%= link_to "Back to customers", customers_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/customers/show.html.erb
<div class="container">
  <h2 class="mb-4 text-center">Payments for <%= @customer.name %></h2>
    
  <%= render "payments_table" %>

  <%= render "missing_payments" %>

  <div class="col-lg-6 col-xxl-4 my-5 mx-auto">
    <div class="d-grid gap-2">
      <%= link_to "Back to customers", customers_path, class: "btn btn-outline-secondary" %>
      <%= link_to "Edit this customer", edit_customer_path(@customer), class: "btn btn-primary" %>
    </div>
  </div>

</div>

app/views/layouts/_header.html.erb
<div class="container">
  <nav class="navbar navbar-expand-lg bg-white border-bottom" aria-label="Navigation">
    <div class="container-fluid">
      <a class="navbar-brand" href="<%= root_path() %>">
        <%= image_tag "fit_fee_logo.png", size: "34x34" %> Fit Fee
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample09">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Home", pages_home_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Customers", customers_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Payments", payments_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/_notice.html.erb
<div class="container mt-2">
  <% if notice %>
    <div class="alert alert-success text-center" role="alert">
      <%= notice %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fit Fee - What matters</title>
    <%= favicon_link_tag 'favicon.ico' %> <!-- Para arquivos .ico -->
    <!-- Ou para outros formatos, como PNG -->
    <%= favicon_link_tag 'favicon.png', rel: 'icon', type: 'image/png' %>
      
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "shared/header" %>

    <%= render partial: "shared/flash" %>

    <main class="container mt-4">
      <%= yield %>
    </main>

  </body>

</html>

app/views/pages/home.html.erb
<div class="bg-white">
  <h1 class="display-1 text-success">Empower Fitness, Simplify Finances</h1>
  <p class="col-lg-8 mx-auto fs-5 text-muted mt-4 p-5" style="text-align: left;">
    Transform your fitness business with our app, designed to streamline client payment management effortlessly. Say goodbye to missed payments and financial mix-ups, and hello to seamless transactions. Elevate your training experience by focusing on what truly matters—your clients' success. It's time to enhance financial transparency and efficiency in your fitness journey.
  </p>
  <div class="d-flex justify-content-center mt-4">
    <%= link_to "Get Started", new_user_registration_path, class: "btn btn-success btn-lg px-4 rounded-pill" %>
  </div>
</div>

app/views/payments/_customers_debts_table.html.erb
<% if @customers_with_debts.empty? %>
  <div class="container mt-5 text-center">
    <div class="bg-body-tertiary p-5 rounded">
      <h1 class="display-4">Great News!</h1>
      <p class="lead">You're all caught up with your payments. Now, you can focus on what truly matters - training with peace of mind and joy.</p>
      <div class="mt-4 d-grid gap-2 d-sm-flex justify-content-sm-center">
        <%= link_to 'Add a new Customer', new_customer_path, class: "btn btn-lg btn-success rounded-pill" %>
      </div>
    </div>
  </div>

<% else %>
  <ul class="list-unstyled">
    <% @customers_with_debts.each do |customer_with_debt| %>
      <li class="mb-3">
        <h3 class="text-center"><%= customer_with_debt[:customer].name %></h3>
        <% customer_with_debt[:missing_payments].each do |payment| %>
          <div class="d-flex justify-content-between align-items-center py-2">
            <span><%= payment[:date].strftime("%B %Y") %></span>
            <%= form_with url: add_missing_payment_customer_payments_path(customer_with_debt[:customer]), method: :post, class: "d-inline" do |form| %>
              <%= form.hidden_field :payment_date, value: payment[:date] %>
              <%= form.hidden_field :amount, value: payment[:amount] %>
              <%= number_to_currency(payment[:amount]) %> <%= form.submit "Paid", class: "btn btn-success btn-sm" %>
            <% end %>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/payments/_form.html.erb
<%= form_with(model: [customer, payment], local: true, html: { class: "needs-validation", novalidate: "" }) do |form| %>
  <% if payment.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading">Please review the following errors:</h4>
      <ul>
        <% payment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :amount, class: 'form-label' %>
    <%= form.number_field :amount, step: 0.01, class: 'form-control', required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :payment_date, class: 'form-label' %>
    <%= form.date_field :payment_date, class: 'form-control', required: true %>
  </div>

  <!-- Removido o campo de seleção do cliente, já que o cliente é pré-definido -->
  
  <div class="text-center">
    <%= form.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/payments/index.html.erb
<% if current_user.customers.count.zero? %>

  <%= render "shared/welcome" %>

<% else %>

  <%= render "customers_debts_table" %>

<% end %>

app/views/payments/new.html.erb
<h1 class="mb-3">New Payment</h1>

<%= render partial: 'form', locals: { payment: @payment, customer: @customer } %>

<%= link_to 'Back to Customer', customer_path(@customer), class: 'btn btn-secondary mt-3' %>

app/views/shared/_flash.html.erb
<div class="container mt-2">
  <% if notice %>
    <div class="alert alert-success text-center" role="alert">
      <%= notice %>
    </div>
  <% end %>
</div>

app/views/shared/_header.html.erb
<div class="container">
  <nav class="navbar navbar-expand-lg bg-white border-bottom" aria-label="Navigation">
    <div class="container-fluid">

      <% if user_signed_in? %>
        <a class="navbar-brand" href="<%= payments_path() %>">
          <%= image_tag "fit_fee_logo.png", size: "34x34" %> Fit Fee
        </a>
      <% else %>
        <a class="navbar-brand" href="<%= root_path() %>">
          <%= image_tag "fit_fee_logo.png", size: "34x34" %> Fit Fee
        </a>
      <% end %>


      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample09">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">

          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Customers", customers_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Payments", payments_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Profile', edit_user_registration_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
          
          <% else %>
            <li class="nav-item">
              <%= link_to "Log in", new_user_session_path, class: "btn btn-success" %>
            </li>
          <% end %>

        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/shared/_welcome.html.erb
<div class="bg-body-tertiary p-5 rounded text-center">
  <h1 class="display-4">Welcome to Fit Fee!</h1>
  <p class="lead">Manage your client payments effortlessly and boost your financial health.</p>
  <div class="mt-4 d-grid gap-2 d-sm-flex justify-content-sm-center">
    <%= link_to 'Add Your First Customer', new_customer_path, class: "btn btn-lg btn-success rounded-pill" %>
  </div>
</div>